# Gradle JVM args — keep heap large enough for Compose compiler.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -XX:+UseParallelGC

# AndroidX
android.useAndroidX=true

# Kotlin
kotlin.code.style=official

# Non-transitive R class for faster builds & smaller artifacts.
android.nonTransitiveRClass=true

# Avoid generating BuildConfig by default in libraries.
android.defaults.buildfeatures.buildconfig=true

# Suppress unsupported warnings on AGP/Kotlin version pairings.
android.suppressUnsupportedCompileSdk=34
